spring:
  redis:
    host: 192.168.0.103
    port: 6379
    password: 
    database: 0
    timeout: 1000
    lettuce:
      pool:
        min-idle: 0
        max-idle: 5
        max-active: 100
        max-wait: 3000
      shutdown-timeout: 100
  cache:
    type: redis

user:
  redis:
    ttl:
      user: 5
