spring:
  redis:
    host: 81.68.182.134
    port: 6379
    password: 514840279@qq.com
    database: 15
    timeout: 1000
    lettuce:
      pool:
        min-idle: 0
        max-idle: 5
        max-active: 100
        max-wait: 3000