server:
  port: 18002
  servlet:    context-path: /serve
  

spring:
  application:    name: chuxue-serve
  banner:    charset: utf-8
  profiles:
    active:
    - nacos
#    - h2
    - mysql
    - hikari
    - redis

