logging:
  level:
    jdbc:
      resultsettable: DEBUG
      sqltiming: DEBUG

server:
  port: 19002
  servlet:
    context-path: /rollcall


spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024000000
      max-request-size: 409600000
      location: /tmp/
      
        
  application:
    name: tools-rollcall
  main:
    banner-mode: CONSOLE
  thymeleaf:
    cache: false
  banner:
    charset: utf-8
  profiles:
    active:
    - h2
    - jpa
    - hikari
    - excutor
    - user
    
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
