server:
  port: 18010
  servlet:
    context-path: /security

spring:
  application:    name: chuxue-security
  web:
    resources:
      static-locations:
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/static/
      - classpath:/public/
      - file:./outputfile/
      - file:./uploadfile/
      - file:./headimg/
  aop:
    proxy-target-class: true
#  datasource:
#    schema:
#    - classpath:sql/schema.sql
#    data: classpath:sql/data.sql
  servlet:
    multipart:
      max-file-size: 100000000
      max-request-size: 100000000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    
  messages:
    basename: /static/i18n/messages #指定国际化文件路径
    encoding: UTF-8

  profiles:
    active:
#    - localhost
    - user
    - mysql8
    - hikari
    - nacos
#    - security
    
