server:
  port: 8001  servlet:    context-path: /
spring:
  application:    name: chuxue-gateway
  banner:    charset: utf-8
  profiles:
    active:
      - gateway
      - nacos

logging:
  level:
    org.springframework.cloud.gateway: info
    com.alibaba.nacos.client.naming: warn            