spring:
  cloud:
    gateway:
      httpclient:
        pool:
          maxIdleTime: 10000 #（根据需要调整）
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
          enabled: true
          lower-case-service-id: true

      routes:
        - id: chuxue-serve
          uri: lb://chuxue-serve
          predicates:
            - Path=/serve/**
            
        - id: chuxue-data-h2
          uri: lb://chuxue-data-h2
          predicates:
            - Path=/data/**
            