server:
  port: 18006
  servlet:    context-path: /data
  

spring:
  application:    name: chuxue-data-oracle
  banner:    charset: utf-8
  profiles:
    active:
    - nacos
    - data-oracle
    - hikari
    - mybatis

