server:
  port: 19003
  servlet:    context-path: /jijin
  

spring:
  application:    name: chuxue-data-h2
  banner:    charset: utf-8
  profiles:
    active:
    - nacos
    - h2
    - hikari
    - mybatis
    
