spring:
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:dbc2m
    #url: jdbc:h2:file:./dbh2/dbc2m;AUTO_SERVER=TRUE
    url: jdbc:h2:tcp://81.68.182.134:9090/jijin;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password: 
