server:
  port: 9001
  servlet:
    context-path: /dataClean
spring:
  application:
    name: data-clean
  main:
    banner-mode: console
  thymeleaf:
    cache: false
  datasource:
    platform: ORACLE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: system
    password: oracle
    url: jdbc:oracle:thin:@192.168.0.105:49161:xe
    #url: jdbc:oracle:thin:@192.168.31.237:1521:orcl  

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # Mybatis实体类属性与数据库表列名对应规则：驼峰转换
    mapUnderscoreToCamelCase: true
    callSettersOnNulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  