server:
  port: 8009
  servlet:
    context-path: /dataClean
spring:
  application:
    name: data-clean
  main:
    banner-mode: console
  thymeleaf:
    cache: false
  datasource:
    platform: ORACLE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: system
    password: oracle
    url: jdbc:oracle:thin:@192.168.0.105:49161:xe
    #url: jdbc:oracle:thin:@192.168.31.237:1521:orcl  

  