server:
  port: 18003
  servlet:
    context-path: /data

spring:
  application:
    name: danyuan-data
  banner:    charset: utf-8
  profiles:
    active:
    - h2
    - hikari
    - nacos
    
  batch:
    job:      names: jdbcItemReadJobDemo    jdbc:      initialize-schema: always  web:    resources:      static-locations:      - classpath:/META-INF/resources/      - classpath:/resources/      - classpath:/static/      - classpath:/public/      - file:./datafile/
      
