server:
  port: 8005
  servlet:    context-path: /data
  

spring:
  application:    name: danyuan-data-mysql
  banner:    charset: utf-8
  profiles:
    active:
    - nacos
    - mysql
    - hikari
