server:
  port: 18005
  servlet:    context-path: /data
  

spring:
  application:    name: chuxue-data-mysql
  banner:    charset: utf-8
  profiles:
    active:
    - nacos
    - data-mysql
    - hikari
    - mybatis
